// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWgQGXZYxhvHJj8P5R4uLtphv9wEvCxp8',
    appId: '1:859085558360:android:47212610df4775f232702d',
    messagingSenderId: '859085558360',
    projectId: 'focusflow-e997f',
    storageBucket: 'focusflow-e997f.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB50g3bKEHY49ll7JU0YwE0O_DZEA3y0w4',
    appId: '1:859085558360:web:a42d8b35f2154eca32702d',
    messagingSenderId: '859085558360',
    projectId: 'focusflow-e997f',
    authDomain: 'focusflow-e997f.firebaseapp.com',
    storageBucket: 'focusflow-e997f.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDftIIL6ab4EUtUBA2anfyq3RwNHAmKXGE',
    appId: '1:859085558360:ios:31c08662bbf52bef32702d',
    messagingSenderId: '859085558360',
    projectId: 'focusflow-e997f',
    storageBucket: 'focusflow-e997f.firebasestorage.app',
    iosClientId: '859085558360-152ssddvcf8qqel4ns58iaf58oca9o4v.apps.googleusercontent.com',
    iosBundleId: 'com.example.focusFlow',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDftIIL6ab4EUtUBA2anfyq3RwNHAmKXGE',
    appId: '1:859085558360:ios:59fb21399d19ee5932702d',
    messagingSenderId: '859085558360',
    projectId: 'focusflow-e997f',
    storageBucket: 'focusflow-e997f.firebasestorage.app',
    iosClientId: '859085558360-kkfbb1737sgn0o08ulp9ep0p7t0kheav.apps.googleusercontent.com',
    iosBundleId: 'com.suraj.focusflow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB50g3bKEHY49ll7JU0YwE0O_DZEA3y0w4',
    appId: '1:859085558360:web:1878c969bd58985332702d',
    messagingSenderId: '859085558360',
    projectId: 'focusflow-e997f',
    authDomain: 'focusflow-e997f.firebaseapp.com',
    storageBucket: 'focusflow-e997f.firebasestorage.app',
  );

}